using LockheedMartin.DeveloperTest.DAL.Models;
using Microsoft.EntityFrameworkCore;
using System;

namespace LockheedMartin.DeveloperTest.DAL
{
    public class SeedData
    {
        public void SetExample(ModelBuilder modelBuilder)
        {
            var weekId = new Guid("82bf8a55-324e-4254-923c-c454f1f1be63");
            modelBuilder.Entity<ForecastWeek>().HasData(new { Id = new Guid("82bf8a55-324e-4254-923c-c454f1f1be63"), Name = "Example Week" });

            modelBuilder.Entity<ForecastTemperature>().HasData(
                //Sunday
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 16M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Sunday, ForecastWeekId = weekId },
                //Monday
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Monday, ForecastWeekId = weekId },
                //Tuesday
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Tuesday, ForecastWeekId = weekId },
                //Wednesday
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Wednesday, ForecastWeekId = weekId },
                //Thursday
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Thursday, ForecastWeekId = weekId },
                //Friday
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Friday, ForecastWeekId = weekId },
                //Saturday
                new { Id = Guid.NewGuid(), TemperatureC = 9M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 15M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 14M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 13M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 12M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 11M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId },
                new { Id = Guid.NewGuid(), TemperatureC = 10M, DayId = DayOfWeek.Saturday, ForecastWeekId = weekId }
            );
        }
    }
}
